"""Secure credential setup.

Prompts for Angel One credentials and writes them to ``.env`` (which is
git-ignored), so secrets never have to be typed into source, shell history or a
chat. Secret fields are read with :func:`getpass` (no echo).
"""

from __future__ import annotations

import getpass
import os
import sys
from pathlib import Path

CREDENTIAL_KEYS = (
    "ANGEL_API_KEY",
    "ANGEL_CLIENT_CODE",
    "ANGEL_PIN",
    "ANGEL_TOTP_SECRET",
)

_SECRET_KEYS = {"ANGEL_PIN", "ANGEL_TOTP_SECRET", "ANGEL_API_KEY"}


def mask(value: str, keep: int = 4) -> str:
    if not value:
        return "(empty)"
    if len(value) <= keep * 2:
        return "*" * len(value)
    return f"{value[:keep]}...{value[-keep:]}"


def _read_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip()
    return data


def _write_env(path: Path, existing: dict[str, str], updates: dict[str, str]) -> None:
    existing.update(updates)
    # preserve everything else as-is; emit a simple KEY=VALUE file
    lines = [
        "# Generated by `python -m banknifty_trading_app.main setup`.",
        "# Keep this file private. It is git-ignored.",
        "",
    ]
    for key, value in existing.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if os.name != "nt":  # best-effort private perms on POSIX
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass


def read_env(path: str | Path = ".env") -> dict[str, str]:
    return _read_env(Path(path))


def update_env(updates: dict[str, str], env_path: str | Path = ".env", example_path: str | Path = ".env.example") -> Path:
    """Merge ``updates`` into ``.env``, seeding defaults from ``.env.example``."""
    env_path = Path(env_path)
    existing: dict[str, str] = {}
    example = Path(example_path)
    if example.exists():
        existing.update(_read_env(example))
    existing.update(_read_env(env_path))
    _write_env(env_path, existing, updates)
    return env_path


def setup_env_interactive(env_path: str | Path = ".env", example_path: str | Path = ".env.example") -> Path:
    env_path = Path(env_path)
    example = Path(example_path)

    print("Angel One credential setup")
    print("==========================")
    print("Input is not echoed for secret fields. Press Enter to keep an existing value.")
    print(f"Writing to: {env_path.resolve()}\n")

    # seed from .env.example (defaults) then any existing .env values
    existing: dict[str, str] = {}
    if example.exists():
        existing.update(_read_env(example))
    existing.update(_read_env(env_path))

    prompts = {
        "ANGEL_API_KEY": "API key",
        "ANGEL_CLIENT_CODE": "Client code (e.g. A12345)",
        "ANGEL_PIN": "PIN",
        "ANGEL_TOTP_SECRET": "TOTP secret (base32, from your authenticator setup)",
    }

    updates: dict[str, str] = {}
    for key in CREDENTIAL_KEYS:
        current = existing.get(key, "")
        hint = f" [{mask(current)}]" if current else ""
        try:
            if key in _SECRET_KEYS:
                value = getpass.getpass(f"{prompts[key]}{hint}: ").strip()
            else:
                value = input(f"{prompts[key]}{hint}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup cancelled.")
            return env_path
        if value:
            updates[key] = value

    # safe defaults
    updates.setdefault("MODE", "paper")
    updates.setdefault("LIVE_TRADING", "false")

    _write_env(env_path, existing, updates)
    print("\nSaved credentials to .env")
    for key in CREDENTIAL_KEYS:
        print(f"  {key}: {mask(_read_env(env_path).get(key, ''))}")
    print("\nMode: paper (live requires MODE=live and LIVE_TRADING=true)")
    print("Next: run   python -m banknifty_trading_app.main check")
    return env_path
